#!/bin/bash

echo "Downloading VTK $VTK_CHECKOUT and building into $VTK_BUILD_DIR"

VTK_URL=https://github.com/Kitware/VTK.git

CMAKE_OPTIONS="-DBUILD_SHARED_LIBS=ON -DVTK_WRAP_TCL=ON -DVTK_WRAP_PYTHON=ON -DVTK_GROUP_TK=ON"

TCL_OPTIONS="-DTCL_INCLUDE_PATH=$TCL_INCLUDE -DTCL_LIBRARY=$TCL_LIB -DTCL_TCLSH=$TCL_SH"

TK_OPTIONS="-DTK_INCLUDE_PATH=$TK_INCLUDE -DTK_LIBRARY=$TK_LIB -DTK_WISH=$TK_WISH"


git clone $VTK_URL

cd $VTK_DIR

git checkout $VTK_CHECKOUT

mkdir build
cd $VTK_BUILD_DIR
cmake $VTK_DIR $CMAKE_OPTIONS $TCL_OPTIONS $TK_OPTIONS
make -j6

cd $BUILD_DIR

