echo "Downloading GDCM $GDCM_CHECKOUT and building in $GDCM_BUILD_DIR"

CMAKE_OPTIONS="-DGDCM_BUILD_DOCBOOK_MANPAGES=OFF -DBUILD_TESTING=OFF\
 -DGDCM_USE_VTK=ON\
 -DGDCM_BUILD_SHARED_LIBS=ON -DVTK_DIR=$VTK_CMAKE_DIR \
 -DCMAKE_INSTALL_PREFIX=$EXTERNALS_DIR"

git clone $GDCM_URL

mkdir $GDCM_BUILD_DIR
cd $GDCM_BUILD_DIR

cmake $GDCM_DIR $CMAKE_OPTIONS

make -j6

make install

cd $BUILD_DIR
